export const GET_QUOTE_REQUEST = 'GET_QUOTE_REQUEST';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const GET_QUOTE_ERROR = 'GET_QUOTE_ERROR';

export const GET_TERMS_REQUEST = 'GET_TERMS_REQUEST';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_TERMS_ERROR = 'GET_TERMS_ERROR';

export const PUT_TERMS_REQUEST = 'PUT_TERMS_REQUEST';
export const PUT_TERMS_SUCCESS = 'PUT_TERMS_SUCCESS';
export const PUT_TERMS_ERROR = 'PUT_TERMS_ERROR';

export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_ERROR = 'GET_COURSES_ERROR';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SEARCH_MODAL_TOGGLE = 'SEARCH_MODAL_TOGGLE';

export const SELECT_TERM = 'SELECT_TERM';

export const GET_SHORTLIST_SUCCESS = 'GET_SHORTLIST_SUCCESS';
export const GET_SHORTLIST_ERROR = 'GET_SHORTLIST_ERROR';
export const GET_SHORTLIST_REQUEST = 'GET_SHORTLIST_REQUEST';
export const POST_SHORTLIST_SUCCESS = 'POST_SHORTLIST_SUCCESS';
export const POST_SHORTLIST_ERROR = 'POST_SHORTLIST_ERROR';
export const POST_SHORTLIST_REQUEST = 'POST_SHORTLIST_REQUEST';
export const DELETE_SHORTLIST_SUCCESS = 'DELETE_SHORTLIST_SUCCESS';
export const DELETE_SHORTLIST_ERROR = 'DELETE_SHORTLIST_ERROR';
export const DELETE_SHORTLIST_REQUEST = 'DELETE_SHORTLIST_REQUEST';

// export const ADD_SHORTLIST = 'ADD_SHORTLIST';
// export const REMOVE_SHORTLIST = 'REMOVE_SHORTLIST';

export const ADD_TO_TERM = 'ADD_TO_TERM';
export const REMOVE_FROM_TERM = 'REMOVE_FROM_TERM';