export const GET_QUOTE_REQUEST = 'GET_QUOTE_REQUEST';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const GET_QUOTE_ERROR = 'GET_QUOTE_ERROR';

export const GET_TERMS_REQUEST = 'GET_TERMS_REQUEST';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_TERMS_ERROR = 'GET_TERMS_ERROR';

export const ADD_TERM_REQUEST = 'ADD_TERMS_REQUEST';
export const ADD_TERM_SUCCESS = 'ADD_TERMS_SUCCESS';
export const ADD_TERM_ERROR = 'ADD_TERMS_ERROR';

export const REMOVE_TERM_REQUEST = 'REMOVE_TERMS_REQUEST';
export const REMOVE_TERM_SUCCESS = 'REMOVE_TERMS_SUCCESS';
export const REMOVE_TERM_ERROR = 'REMOVE_TERMS_ERROR';

export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_ERROR = 'GET_COURSES_ERROR';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SEARCH_MODAL_TOGGLE = 'SEARCH_MODAL_TOGGLE';

export const SELECT_TERM = 'SELECT_TERM';

export const GET_SHORTLIST_SUCCESS = 'GET_SHORTLIST_SUCCESS';
export const GET_SHORTLIST_ERROR = 'GET_SHORTLIST_ERROR';
export const GET_SHORTLIST_REQUEST = 'GET_SHORTLIST_REQUEST';
export const POST_SHORTLIST_SUCCESS = 'POST_SHORTLIST_SUCCESS';
export const POST_SHORTLIST_ERROR = 'POST_SHORTLIST_ERROR';
export const POST_SHORTLIST_REQUEST = 'POST_SHORTLIST_REQUEST';
export const DELETE_SHORTLIST_SUCCESS = 'DELETE_SHORTLIST_SUCCESS';
export const DELETE_SHORTLIST_ERROR = 'DELETE_SHORTLIST_ERROR';
export const DELETE_SHORTLIST_REQUEST = 'DELETE_SHORTLIST_REQUEST';

export const GET_TERM_COURSES_REQUEST = 'GET_TERM_COURSES_REQUEST';
export const GET_TERM_COURSES_SUCCESS = 'GET_TERM_COURSES_SUCCESS';
export const GET_TERM_COURSES_ERROR = 'GET_TERM_COURSES_ERROR';
export const ADD_TERM_COURSE_REQUEST = 'ADD_TERM_COURSE_REQUEST';
export const ADD_TERM_COURSE_SUCCESS = 'ADD_TERM_COURSE_SUCCESS';
export const ADD_TERM_COURSE_ERROR = 'ADD_TERM_COURSE_ERROR';
export const REMOVE_TERM_COURSE_REQUEST = 'REMOVE_TERM_COURSE_REQUEST';
export const REMOVE_TERM_COURSE_SUCCESS = 'REMOVE_TERM_COURSE_SUCCESS';
export const REMOVE_TERM_COURSE_ERROR = 'REMOVE_TERM_COURSE_ERROR';
export const MOVE_TERM_COURSE_REQUEST = 'MOVE_TERM_COURSE_REQUEST';
export const MOVE_TERM_COURSE_SUCCESS = 'MOVE_TERM_COURSE_SUCCESS';
export const MOVE_TERM_COURSE_ERROR = 'MOVE_TERM_COURSE_ERROR';

export const GET_PROGRAMS_REQUEST = 'GET_PROGRAMS_REQUEST';
export const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
export const GET_PROGRAMS_ERROR = 'GET_PROGRAMS_ERROR';